title: V2Ray VPN User Guide
description: Guide to use V2Ray VPN Client on Mobile, Windows, Linux and Mac, such as V2RayNG for Android, Shadowrocket for iOS.
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day